### ISSUE TITLE
Login Error: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by qokelate** [liuzhuoling2011/baidupcs-web#130]
```
检测BDUSS有效性网络错误, Post http://tieba.baidu.com/c/s/login: dial tcp [2400:da00:5f26:400::6f2d:b2f]:80: connect: network is unreachable
2019/03/17 16:29:06 http: panic serving 192.168.16.1:53255: runtime error: invalid memory address or nil pointer dereference
goroutine 37 [running]:
net/http.(*conn).serve.func1(0xc00091e140)
	/usr/local/go/src/net/http/server.go:1746 +0xd0
panic(0x92f180, 0xe50470)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/iikira/BaiduPCS-Go/internal/pcsweb.WSLogin(0xc00093a1b0, 0xc0009320d0, 0x0, 0x0)
	/mnt/hgfs/share/go/src/github.com/iikira/BaiduPCS-Go/internal/pcsweb/websocket.go:96 +0x442
github.com/iikira/BaiduPCS-Go/internal/pcsweb.WSHandler(0xc00093a1b0)
	/mnt/hgfs/share/go/src/github.com/iikira/BaiduPCS-Go/internal/pcsweb/websocket.go:159 +0x367
golang.org/x/net/websocket.Server.serveWebSocket(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/mnt/hgfs/share/go/src/golang.org/x/net/websocket/server.go:89 +0x17e
golang.org/x/net/websocket.Handler.ServeHTTP(0x9f5340, 0xa69f20, 0xc000178380, 0xc000938300)
	/mnt/hgfs/share/go/src/golang.org/x/net/websocket/server.go:112 +0x86
net/http.(*ServeMux).ServeHTTP(0xe64b40, 0xa69f20, 0xc000178380, 0xc000938300)
	/usr/local/go/src/net/http/server.go:2361 +0x127
net/http.serverHandler.ServeHTTP(0xc000087e10, 0xa69f20, 0xc000178380, 0xc000938300)
	/usr/local/go/src/net/http/server.go:2741 +0xab
net/http.(*conn).serve(0xc00091e140, 0xa6a5e0, 0xc000930300)
	/usr/local/go/src/net/http/server.go:1847 +0x646
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2851 +0x2f5
```

**Comment by qokelate** [comment]
BaiduPCS-Go-3.6.4-linux-amd64.zip

**Comment by liuzhuoling2011** [comment]
试试最新的版本3.6.5

**Comment by qokelate** [comment]
version: BaiduPCS-Go-3.6.5-linux-amd64.zip
uname: Linux 3.10.0-957.5.1.el7.x86_64 #1 SMP Fri Feb 1 14:54:57 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

```
检测BDUSS有效性网络错误, Post http://tieba.baidu.com/c/s/login: dial tcp [2400:da00:5f26:400::6f2d:b2f]:80: connect: network is unreachable
2019/03/21 00:00:15 http: panic serving 47.106.159.141:42784: runtime error: invalid memory address or nil pointer dereference
goroutine 420253 [running]:
net/http.(*conn).serve.func1(0xc000c42140)
        /usr/local/go/src/net/http/server.go:1746 +0xd0
panic(0x934e80, 0xe5b480)
        /usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/iikira/BaiduPCS-Go/internal/pcsweb.WSLogin(0xc000b4e2d0, 0xc000941920, 0x0, 0x0)
        /mnt/hgfs/share/go/src/github.com/iikira/BaiduPCS-Go/internal/pcsweb/websocket.go:96 +0x442
github.com/iikira/BaiduPCS-Go/internal/pcsweb.WSHandler(0xc000b4e2d0)
        /mnt/hgfs/share/go/src/github.com/iikira/BaiduPCS-Go/internal/pcsweb/websocket.go:162 +0x367
golang.org/x/net/websocket.Server.serveWebSocket(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /mnt/hgfs/share/go/src/golang.org/x/net/websocket/server.go:89 +0x17e
golang.org/x/net/websocket.Handler.ServeHTTP(0x9fc078, 0xa71400, 0xc000b220e0, 0xc000100300)
        /mnt/hgfs/share/go/src/golang.org/x/net/websocket/server.go:112 +0x86
net/http.(*ServeMux).ServeHTTP(0xe6fba0, 0xa71400, 0xc000b220e0, 0xc000100300)
        /usr/local/go/src/net/http/server.go:2361 +0x127
net/http.serverHandler.ServeHTTP(0xc00017eb60, 0xa71400, 0xc000b220e0, 0xc000100300)
        /usr/local/go/src/net/http/server.go:2741 +0xab
net/http.(*conn).serve(0xc000c42140, 0xa71ac0, 0xc000a60440)
        /usr/local/go/src/net/http/server.go:1847 +0x646
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2851 +0x2f5
```

**Comment by liuzhuoling2011** [comment]
是不是你BDUSS过期了， 重新用账号密码登陆一下试试
