### ISSUE TITLE
源码编译有指导吗？error Command failed with exit code 1.

### ISSUE THREAD

**Issue by bao3** [liuzhuoling2011/baidupcs-web#204]
OS： FreeBSD (和 macOS darwin 架构一样）

wget 了  source.tar.gz ，使用 node install ，就会出现如下的错误：

```
WARN  "baseUrl" option in vue.config.js is deprecated now, please use "publicPath" instead.
 INFO  Starting development server...
 10% building 2/2 modules 0 activeevents.js:180
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND compile
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26)
Emitted 'error' event at:
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1412:12)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:17) {
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'compile'
}
error Command failed with exit code 1.


```

**Comment by liuzhuoling2011** [comment]
可以检查一下node的版本. 尝试一下升级到最新版?
